apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  creationTimestamp: "2022-05-06T11:26:46Z"
  labels:
    app: e-commerce
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:externalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":80,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: GoogleCloudConsole
    operation: Update
    time: "2022-05-06T11:26:45Z"
  name: e-commerce-service
  namespace: default
  resourceVersion: "10833"
  uid: 72abf2f4-1879-473f-b74d-802a0504fa0c
spec:
  clusterIP: 10.76.0.200
  clusterIPs:
  - 10.76.0.200
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30392
    port: 80
    protocol: TCP
    targetPort: 3001
  selector:
    app: e-commerce
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
